# Generated by Django 4.0.6 on 2022-07-29 15:00

from django.db import migrations, models
import pwitter.validators


class Migration(migrations.Migration):

    dependencies = [
        ('pwitter', '0004_alter_profile_user_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='pweet',
            name='media',
            field=models.FileField(blank=True, upload_to='pweet_media/', validators=[pwitter.validators.FileValidator(content_types=('image/jpeg', 'image/png'), max_size=1024000)]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_image',
            field=models.FileField(blank=True, upload_to='profile_pictures/', validators=[pwitter.validators.FileValidator(content_types=('image/jpeg', 'image/png'), max_size=1024000)]),
        ),
    ]
