# Generated by Django 4.0.6 on 2022-08-01 08:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import pwitter.validators


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pwitter', '0006_pweet_likes_pweetreply'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pweet',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='pweet',
            name='media',
        ),
        migrations.RemoveField(
            model_name='pweetreply',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='pweetreply',
            name='media',
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.FileField(blank=True, upload_to='pweet_media/', validators=[pwitter.validators.FileValidator(content_types=('image/jpeg', 'image/png'), max_size=1024000)])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creates', models.DateTimeField(auto_now_add=True)),
                ('picture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pwitter.picture')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='pweet',
            name='picture',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='pwitter.picture'),
        ),
        migrations.AddField(
            model_name='pweetreply',
            name='picture',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='pwitter.picture'),
        ),
    ]
