# Generated by Django 4.0.6 on 2022-08-02 13:21

from django.db import migrations, models
import django.db.models.deletion
import pwitter.validators


class Migration(migrations.Migration):

    dependencies = [
        ('pwitter', '0009_alter_pweetreply_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='pweet',
            name='user_image',
            field=models.FileField(blank=True, upload_to='pweet_media/', validators=[pwitter.validators.FileValidator(content_types=('image/jpeg', 'image/png'), max_size=1024000)]),
        ),
        migrations.AlterField(
            model_name='pweet',
            name='picture',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='pwitter.picture'),
        ),
    ]
