# Generated by Django 4.0.6 on 2022-08-02 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pwitter', '0010_pweet_user_image_alter_pweet_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pweet',
            old_name='user_image',
            new_name='pweet_image',
        ),
    ]
