# Generated by Django 4.0.6 on 2022-08-04 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pwitter', '0011_rename_user_image_pweet_pweet_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pweet',
            name='picture',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='pwitter.picture'),
        ),
    ]
