# Generated by Django 4.0.6 on 2022-08-05 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pwitter', '0014_alter_picture_pweet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pweetreply',
            name='picture',
        ),
        migrations.AddField(
            model_name='picture',
            name='pweet_reply',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='pwitter.pweetreply'),
        ),
        migrations.AlterField(
            model_name='pweetreply',
            name='reply',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='pwitter.pweet'),
        ),
    ]
