# Generated by Django 4.0.6 on 2022-08-08 10:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pwitter', '0018_remove_like_creates_remove_like_picture_like_pweet_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pweet',
            name='likes',
            field=models.ManyToManyField(related_name='pweet_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
