# Generated by Django 4.0.6 on 2022-08-09 12:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pwitter', '0021_pweetreply_likes_alter_pweet_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pweet',
            name='likes',
            field=models.ManyToManyField(null=True, related_name='pweet_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pweetreply',
            name='likes',
            field=models.ManyToManyField(null=True, related_name='pweet_replies', to=settings.AUTH_USER_MODEL),
        ),
    ]
